config/routes.rb
Rails.application.routes.draw do
  root to: 'lists#index'
  resources :bookmarks, only: [:destroy]
  resources :movies, only: [:index, :show]
  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only:  [:new, :create] do
      resources :movies, only: [:index, :show]
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  # validates :comment, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :lists, through: :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true

  include PgSearch::Model
  pg_search_scope :global_search,
  against: [ :title, :overview, :english_title, :rating ],
  associated_against: {
    # director: [ :first_name, :last_name ]
  },
  using: {
    tsearch: { prefix: true }
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def index
    @bookmarks = Bookmark.all
  end

  def show
    @bookmark = Bookmark.find(params[:id])
  end

  def edit
    @bookmark = Bookmark.find(params[:id])
  end

  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
    @bookmark.list = @list
    @bookmark.save
    @movies = Movie.all.limit(200)
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @movie = Movie.find(params[:bookmark][:movie])
    @bookmark.list = @list
    @bookmark.movie = @movie
    if @bookmark.save
      respond_to do |format|
        format.html { redirect_to list_path(@list) }
        format.text { redirect_to root_path, formats: [:html] }
      end
    else
      raise
    end
  end
  
  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list_id)
  end
  
  private
  
  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    
    @list = List.find(1)
    @bookmark = Bookmark.new
    @movies = Movie.all.limit(50)

        if params[:query].present?
          @movies = @movies.global_search(params[:query]).limit(15)
          respond_to do |format|
            format.html
            format.text { render partial: 'movies/list', locals: { movies: @movies, bookmark: @bookmark }, formats: [:html] }
          end
        else
          @movies = Movie.all.limit(50)
        end
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movie_helper.rb
module MovieHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/cache.html.erb
      <% @list.bookmarks.each do |bookmark| %>
        <div data-controller="hello" class="col show-form-card col-md-4 col-lg-4 my-3">
          <div  class="card-trip">
              <a href="#" class= "form-poster" data-action="click->hello#displayForm"><%= image_tag bookmark.movie.poster_url, class: "form-poster" %></a>
              <div data-hello-target="infos" class="add d-flex align-items-center justify-content-between">
                <h2 class="my-3" id="add-title"><%= bookmark.movie.title %></h2>
                <div data-action="click->hello#displayForm" class="btn add-btn">+</div>
              </div>
            <div  data-hello-target="form" class="d-none card-trip-infos">
              <%= simple_form_for bookmark, html: { class: "d-non", data: { edit_movie_target: "form" } } do |f| %>
              <%= f.input :comment, label: "Leave a comment:",as: :text %>
          
              <div class="from-form d-flex">
                  <%= f.submit "Add", class: 'btn col-4 submit-form btn-success mt-3' %>
              <div data-action="click->hello#cancelForm" class="btn" style="font-size: 8px;">cancel</div>
              </div>
            <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>

app/views/bookmarks/create.html.erb
<h1>Bookmarks#create</h1>
<p>Find me in app/views/bookmarks/create.html.erb</p>

app/views/bookmarks/new.html.erb
<div data-controller="search-movies">
  <div class="container">
    <div class="row">
      <div class="col col-md-4 mt-5 center" style="margin: auto; width: fit-content;">
        <h1 class="mb-3" >📣 🍿 Movies 🎬 📸</h1>
      </div>
      <div class="center">
        <%= form_with url: movies_path, method: :get, html: { class:
          'col-12 col-md-4 center margin-auto mb-4', data: { search_movies_target: 'form' } } do |f| %>
          <%= f.hidden_field(:list_id, :value => params[:list_id])%>  
          <%= f.text_field :query,
                          class: "center-text form-control",
                          placeholder: 'Search',
                          value: params[:query],
                          data: {
                            search_movies_target: 'input',
                          action: 'keyup->search-movies#update'
                        } %>
                          <% end %>
        </div>
        <%= link_to "cancel", list_path(@list), class: "btn kill-link kill-decoration mb-5", id: "cancel-form" %>
  </div>
  <div class="display" data-search-movies-target="list">
  <%= render "movies/list" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%# Google fonts links %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <%# Roboto import, Sans Serif %>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;500&display=swap" rel="stylesheet">
    <%= favicon_link_tag asset_path('favicon.ico') %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="nav-bar m-0">
      <div class="nav-bar-contents">
        <div id="pop-corn"><%= link_to "🍿", lists_path %></div>
        <div class="links">
          <%= link_to "My Lists", lists_path, class: "btn white nav-bar-links mobile-padding" %>
          <%= link_to "New List", new_list_path, class: "btn white nav-bar-links mobile-padding-end" %>
        </div>
      </div>
    </div>

      <div class="container-yield" style="background-color: #EFEFEF;">
        <%= yield %>
      </div>


    <div class="footer row m-0">
        <div class="footer-contents end links">
          <a href="#" class="links btn ml-2 mr-2">Made with love, at home</a>
        </div>
    </div>
  </body>
</html>

app/views/lists/borrador.html.erb
<%# Search input centered for phone, eventually to be used to search for movies %>
  <div class="col-1 col-md-4">
  </div>
  <div class="col-4" data-controller="hello" style="width: 100%;">
    <form class="d-flex" style="margin-top: 20px;" data-action="submit->hello#search">
      <input type="text" class="form-control flex-grow-1 me-2" placeholder="Not connected yet" data-map-target="query">
      <input type="submit" value="Go!" class="btn btn-primary">
    </form>
  </div>
  <div class="col-1 col-md-4">
  </div>
  </div>




 <div class="btn-wrap">
    <h3 class="btn btn-warning banner-btn-kill lighter counter">
      <%=@list.movies.count%> <%=@list.movies.count == 1 ?  'movie' : 'movies' %>
    </h3>
  </div>

  <h1 style="height: 700px;"><%= @list.name.capitalize %></h1>

app/views/lists/create.html.erb
<h1>Lists#create</h1>
<p>Find me in app/views/lists/create.html.erb</p>

app/views/lists/index.html.erb
<div class="banner shadow" style="background-image: url('https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=3270&q=80');"><div class="mb-5 banner-text"><h1 class="pb-1 m-0" data-controller="hello">Save any kind of movies</h1>
  <%= link_to "Add a list", new_list_path, class: "btn btn-primary mt-4 px-5" %>
  <%  %>
  </div>


</div></div>


<div class="container">
  <div class="row above-lists-contents mt-3 mb-3">
      <p id="add-list-btn"><%= link_to "Create a movie list", new_list_path, class:"btn btn-primary white mt-3 mb-3"%></p>
  </div>

  <div class="row">

    <div class="if-no-movie">
      <p style="<%= @lists.count == 0 ? 'height: 50vh; display: flex; align-items: center; justify-content: center;' : '' %>">
      <% if @lists.count == (0) %>
      <a href="/lists/new" class="btn">Wanna add a list?</a>
      <% else %>
      <% end %>
      </p>
    </div>

    <% @lists.each do |list| %>
      <div class="col-lg-4 col-md-4 col-sm-12 center">
          <div class="my-card" style=" background-image: url('https://picsum.photos/2000/3000?<%= rand(1..500) %>');">

                <%= link_to list.name.capitalize, list_path(list), class: "col btn white index-shadow", style: "padding: 0;" %>
                <%= link_to "+" , new_list_bookmark_path(list), class: "add-direct-btn white kill-decoration index-shadow" %>

          </div>
      </div>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<div class="container">
  <div class="row">

    <div class="col-1 col-md-4">
    </div>

    <div class="col col-md-4 mt-5">
      <h1 class="mb-3">Add a list</h1>

      <%= simple_form_for [@list] do |f| %>
      <%= f.input :name %>
      <%= f.button :submit, "Finished", class: "btn btn-primary mt-3 mb-1" %>
      <% end %>
      <%= link_to "cancel", lists_path, class: "btn kill-link kill-decoration", id: "cancel-form" %>
    </div>

     <div class="col-1 col-md-4">
     </div>

  </div>
</div>

app/views/lists/show.html.erb
<div class="banner-show" style="background-image: url('https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=3270&q=80');">
</div>



<div class="container">
  <div class="above-lists-contents mt-3">
    <div class="above-list-left">
      <div class="back-btn"><a href="/lists" class = "btn back-btn-txt kill-decoration black lighter" style="padding-left: 0;" id = "back-btn"><i class="fa-solid fa-angles-left"></i></div>
      <h3 class="btn banner-btn-kill lighter counter" style="padding-left: 0;">
        (<%=@list.movies.count%>) <%=@list.movies.count == 1 ?  'movie' : 'movies' %>
      </h3>
    </div>
    </a>
      <div id="add-movie-btn"><%= link_to "add a movie", new_list_bookmark_path(@list), class: "btn btn-primary color-white" %></div>
  </div>
   <div class="row justify-content-center">

    <div class="if-no-movie">
      <p style="text-align: center;<%= @list.movies.count == 0 ? 'height: 50vh; display: flex; align-items: center; justify-content: center;' : '' %>">
        <% if @list.movies.count == (0) %>
        <a href="/lists/<%= @list.id %>/bookmarks/new" class="btn">Wanna add a movie?</a>
        <% else %>
        <% end %>
      </p>
    </div>

    <% @list.bookmarks.each do |bookmark| %>
      <div class="col col-md-4 col-lg-4 mt-5">
        <div class="card-trip mb-5">
            <%= image_tag bookmark.movie.poster_url, class: "poster" %>
          <div class="card-trip-infos">
            <div>
              <h2 class="mt-2 mb-2" id="card-title"><%= bookmark.movie.title %></h2>
              <p class="overview overflow-scroll mt-2"><%= bookmark.movie.overview %></p>
            </div>
              <div class="card-bottom mb-2 mt-2">
                <div class="card-bottom-left">
                  <span class="comment"><i class="fas fa-quote-left"></i> <%= bookmark.movie.bookmarks.last.comment.strip%></span>
                </div>
                <div class="card-bottom-right">
                  <h2 class="card-trip-pricing mt-2"><%= '⭐' * bookmark.movie.rating.to_i.round  %> </h2>
                  <%= button_to "Delete", bookmark_path(bookmark.id), method: :delete, style: "color: red;",class: "mt-2 text-small kill-decoration ew" %>
                </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/lists/test.html.erb
    <% @list.movies.each do |movie| %>
      <div class="col col-lg-4 mt-5">
        <div class="card-trip mb-5">
            <%= image_tag movie.poster_url, class: "poster" %>
          <div class="card-trip-infos">
            <div>
              <h2 class="mt-2 mb-2" id="card-title"><%= movie.title %></h2>
              <p class="mt-2"><%= movie.overview %></p>
            </div>
              <div class="card-bottom mb-2 mt-2">
                <div class="card-bottom-left">
                  <span class="comment p-3"><%= movie.bookmarks.last.comment %></span>
                </div>
                <div class="card-bottom-right">
                  <h2 class="card-trip-pricing mt-2"><%= '⭐' * movie.rating.round  %> </h2>
                  <%= link_to "Delete", bookmark_path(movie.bookmark.id), method: :delete, style: "color: red;", class: "mt-2 text-small" %>
                </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>

app/views/movies/_list.html.erb
<div data-controller="search-movies">
  <div class="target" data-search-movies-target="list form">
      <% @movies.each do |movie| %>
        <div data-controller="hello" class="col show-form-card col-md-4 col-lg-4 my-3">
          <div  class="card-trip" id="<%= movie.id %>">
              <a href="#" class= "form-poster" data-hello-target="image1" data-action="click->hello#displayForm"><%= image_tag movie.poster_url, class: "form-poster" %></a>
              <a href="#" class= "d-none form-poster" data-hello-target="image2" data-action="click->hello#cancelForm"><%= image_tag movie.poster_url, class: "form-poster" %></a>
              <div data-hello-target="infos" class="add d-flex align-items-center justify-content-between">
                <h2 class="btn my-3" id="add-title" data-action="click->hello#displayForm"><%= movie.title %></h2>
                <div data-action="click->hello#add" class="btn add-btn">+</div>
              </div>
            <div  data-hello-target="remove" class="d-none card-trip-infos">
             <h2 class="btn my-3" id="add-title", style="margin-top: 0px!important; margin-left: 0px; padding: 0px;" data-action="click->hello#cancelForm"><%= movie.title %></h2>
              <p style="height: 73px; overflow: scroll;"><%= movie.overview %></p>
               <%= simple_form_for [@list, @bookmark], html: { class: "mt-3", id: "form_id", data: { hello_target: "form", action: 'submit->hello#add' } } do |f| %>
               <%= f.input :comment,label: "Leave a comment:", as: :text %> 
               <%= f.hidden_field :movie, :value => movie.id %> 
              <div class="from-form d-flex">
                   <%= f.submit "Add", class: 'center btn col-4 submit-form btn-success mt-3' %> 
                 <div data-action="click->hello#cancelForm" class="btn" style="font-size: 8px; width: fit-content; margin: auto;">cancel</div>
              </div>

             <% end %>
            </div>
          </div>
        </div>
      <% end %>
  </div>
</div>

app/views/movies/index.html.erb
<div data-controller="search-movies">
  <div class="container">
    <div class="row">
      <div class="col col-md-4 mt-5 center" style="margin: auto; width: fit-content;">
        <h1 class="mb-3" >📣 🍿 Movies 🎬 📸</h1>
      </div>
      <div class="center">
        <%= form_with url: movies_path, method: :get, html: { class:
          'col-12 col-md-4 center margin-auto mb-4', data: { search_movies_target: 'form' } } do |f| %>
          <%= f.hidden_field(:list_id, :value => params[:list_id])%>  
          <%= f.text_field :query,
                          class: "center-text form-control",
                          placeholder: 'Search',
                          value: params[:query],
                          data: {
                            search_movies_target: 'input',
                          action: 'keyup->search-movies#update'
                        } %>
                          <% end %>
        </div>
        <%# <%= link_to "cancel", list_path(@list), class: "btn kill-link kill-decoration mb-5", id: "cancel-form" %> 
  </div>
  <div class="display" data-search-movies-target="list">
  <%= render "movies/list" %>
</div>

app/views/movies/show.html.erb
<h1>Movie#show</h1>
<p>Find me in app/views/movie/show.html.erb</p>